def test_expected_failure(self):


    class Foo(unittest2.TestCase):

        @unittest2.expectedFailure
        def test_die(self):
            self.fail('help me!')
    events = []
    result = LoggingResult(events)
    test = Foo('test_die')
    test.run(result)
    self.assertEqual(events, ['startTest', 'addExpectedFailure', 'stopTest'])
    self.assertEqual(result.expectedFailures[0][0], test)
    self.assertTrue(result.wasSuccessful())
