def test_init__test_name__invalid(self):


    class Test(unittest2.TestCase):

        def runTest(self):
            raise MyException()

        def test(self):
            pass
    try:
        Test('testfoo')
    except ValueError:
        pass
    else:
        self.fail('Failed to raise ValueError')
