def testCleanUpWithErrors(self):


    class TestableTest(unittest2.TestCase):

        def testNothing(self):
            pass


    class MockResult(object):
        errors = []

        def addError(self, test, exc_info):
            self.errors.append((test, exc_info))
    result = MockResult()
    test = TestableTest('testNothing')
    test._resultForDoCleanups = result
    exc1 = Exception('foo')
    exc2 = Exception('bar')

    def cleanup1():
        raise exc1

    def cleanup2():
        raise exc2
    test.addCleanup(cleanup1)
    test.addCleanup(cleanup2)
    self.assertFalse(test.doCleanups())
    ((test1, (Type1, instance1, _)), (test2, (Type2, instance2, _))) = reversed(MockResult.errors)
    self.assertEqual((test1, Type1, instance1), (test, Exception, exc1))
    self.assertEqual((test2, Type2, instance2), (test, Exception, exc2))
