def _print_ant_failure_and_exit(self, ant_log_path):
    print(textwrap.dedent("                ::: 'ant' failed in the buck repo at '{0}',\n                ::: and 'buck' is not properly built. It will be unusable\n                ::: until the error is corrected. You can check the logs\n                ::: at {1} to figure out what broke.".format(self._buck_dir, ant_log_path)), file=sys.stderr)
    if self._is_git:
        raise BuckRepoException(textwrap.dedent('                ::: It is possible that running this command will fix it:\n                ::: git -C "{0}" clean -xfd'.format(self._buck_dir)))
    else:
        raise BuckRepoException(textwrap.dedent('                ::: It is possible that running this command will fix it:\n                ::: rm -rf "{0}"/build'.format(self._buck_dir)))
