{
  LOG.warn(t,"Build error caused by exception");
  printBuildFailureInternal(t.getMessage());
}
