def addExpectedFailure(self, test, err):
    'Called when an expected failure/error occured.'
    self.expectedFailures.append((test, self._exc_info_to_string(err, test)))
