def fail(self, msg=None):
    'Fail immediately, with the given message.'
    raise self.failureException(msg)
