def test_that_fails(self):
    self.fail('failure')
